---
num_labels: 3 # How many values should activation/valence be binned into
audio_feature_type: 'facebook/wav2vec2-base' # What audio features should the dataset return ('raw', 'mfb', or huggingface wav2vec2 string)
text_feature_type: 'google/bert_uncased_L-4_H-512_A-8' # What text features should the dataset return ('raw', or huggingface BERT string)
min_len: 2 # Minimum audio length (seconds)
max_len: 15 # Maximum audio length (seconds)
ASR:
  permit_ASR: False # Should ASR be allowed when transcripts are missing
  azure_secrets_path: '' # If so, provide path to azure secrets file for ASR
SR: 16000
mfb_settings:
  n_fft: 2048
  n_mels: 40
  hop_length: 160
  fmin: 0
  fmax: None
  clamp_val: 3.0
  clamp_values: True
iemocap_directory: '/z/public/data/IEMOCAP_full_release'
improv_directory: '/z/public/data/MSP_IMPROV'
podcast_directory: '/z/public/data/MSP_Podcast'
muse_directory: '/z/public/data/MuSE'