---
num_labels: 3 # How many values should activation/valence be binned into
audio_feature_type: 'raw' # What audio features should the dataset return ('raw', 'mfb', or huggingface wav2vec2 string)
text_feature_type: 'raw' # What text features should the dataset return ('raw', or huggingface BERT string)
min_len: 2 # Minimum audio length (seconds)
max_len: 15 # Maximum audio length (seconds)
ASR:
  permit_ASR: False # Should ASR be allowed when transcripts are missing
  azure_secrets_path: '' # If so, provide path to azure secrets file for ASR