[project]
name = "SERDatasets"
version = "1.0.0"
description = "Code for loading and processing some common SER datasets"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
